CREATE TABLE IF NOT EXISTS persons (
  id SERIAL PRIMARY KEY,
  last_name varchar(255),
  first_name varchar(255),
  address varchar(255),
  city varchar(255),
  state varchar(255)
);

INSERT INTO persons (id, last_name, first_name, address, city, state)
SELECT 1, 'John', 'Doe', '1234 EXAMPLE ROAD', 'Chicago', 'Illinois'
WHERE NOT EXISTS (
  SELECT 'X'
  FROM persons
  WHERE id = 1 AND first_name = 'John' AND last_name = 'Doe'
);
